const Map<String, String> highlightImages = {
  // Hunza Valley
  'Baltit Fort': 'assets/images/highlights/baltit_fort.jpg',
  'Attabad Lake': 'assets/images/highlights/attabad_lake.jpg',
  'Passu Cones': 'assets/images/highlights/passu_cones.jpg',
  'Khunjerab Pass': 'assets/images/highlights/khunjerab_pass.jpg',
  'Altit Fort': 'assets/images/highlights/altit_fort.jpg',
  "Eagle's Nest Duikar": 'assets/images/highlights/eagles_nest_duikar.jpg',
  'Borith Lake': 'assets/images/highlights/borith_lake.jpg',
  'Rakaposhi View Point': 'assets/images/highlights/rakaposhi_view_point.jpg',
  'Hussaini Suspension Bridge': 'assets/images/highlights/hussaini_suspension_bridge.jpg',
  'Karimabad Bazaar': 'assets/images/highlights/karimabad_bazaar.jpg',

  // Skardu & Shangrila
  'Shangrila Resort': 'assets/images/highlights/shangrila_resort.jpg',
  'Upper Kachura Lake': 'assets/images/highlights/upper_kachura_lake.jpg',
  'K2 Base Camp': 'assets/images/highlights/k2_base_camp.jpg',
  'Deosai Plains': 'assets/images/highlights/deosai_plains.jpg',
  'Lower Kachura Lake': 'assets/images/highlights/lower_kachura_lake.jpg',
  'Skardu Fort': 'assets/images/highlights/skardu_fort.jpg',
  'Satpara Lake': 'assets/images/highlights/satpara_lake.jpg',
  'Shigar Fort': 'assets/images/highlights/shigar_fort.jpg',
  'Blind Lake': 'assets/images/highlights/blind_lake.jpg',
  'Manthoka Waterfall': 'assets/images/highlights/manthoka_waterfall.jpg',

  // Swat Valley
  'Malam Jabba': 'assets/images/highlights/malam_jabba.jpg',
  'Mahodand Lake': 'assets/images/highlights/mahodand_lake.jpg',
  'White Palace': 'assets/images/highlights/white_palace.jpg',
  'Waterfalls': 'assets/images/highlights/waterfalls.jpg',
  'Kalam Valley': 'assets/images/highlights/kalam_valley.jpg',
  'Bahrain': 'assets/images/highlights/bahrain.jpg',
  'Ushu Forest': 'assets/images/highlights/ushu_forest.jpg',
  'Fizagat Park': 'assets/images/highlights/fizagat_park.jpg',
  'Swat Museum': 'assets/images/highlights/swat_museum.jpg',
  'Mingora City': 'assets/images/highlights/mingora_city.jpg',

  // Naran & Kaghan
  'Saif-ul-Mulook': 'assets/images/highlights/saif_ul_mulook.jpg',
  'Lulusar Lake': 'assets/images/highlights/lulusar_lake.jpg',
  'Babusar Top': 'assets/images/highlights/babusar_top.jpg',
  'Pine Forests': 'assets/images/highlights/pine_forests.jpg',
  'Lalazar Meadow': 'assets/images/highlights/lalazar_meadow.jpg',
  'Shogran': 'assets/images/highlights/shogran.jpg',
  'Siri Paye Meadows': 'assets/images/highlights/siri_paye_meadows.jpg',
  'Ansoo Lake': 'assets/images/highlights/ansoo_lake.jpg',
  'Noori Top': 'assets/images/highlights/noori_top.jpg',
  'Jalkhad': 'assets/images/highlights/jalkhad.jpg',

  // Fairy Meadows
  'Nanga Parbat View': 'assets/images/highlights/nanga_parbat_view.jpg',
  'Beyal Camp': 'assets/images/highlights/beyal_camp.jpg',
  'Jhelum Meadows': 'assets/images/highlights/jhelum_meadows.jpg',
  'Trekking': 'assets/images/highlights/trekking.jpg',
  'Raikot Bridge': 'assets/images/highlights/raikot_bridge.jpg',
  'Tattu Village': 'assets/images/highlights/tattu_village.jpg',
  'Nanga Parbat Base Camp': 'assets/images/highlights/nanga_parbat_base_camp.jpg',
  'Rupal Valley': 'assets/images/highlights/rupal_valley.jpg',
  'Fairy Point': 'assets/images/highlights/fairy_point.jpg',
  'Raikot Glacier': 'assets/images/highlights/raikot_glacier.jpg',

  // Shigar Valley (sample_data.dart)
  'Katpana Cold Desert': 'assets/images/highlights/skardu_fort.jpg',
  'Basho Valley': 'assets/images/highlights/shigar_fort.jpg',
  'Mantho Kha Waterfall': 'assets/images/highlights/manthoka_waterfall.jpg',
  'Hashupi Rock Carvings': 'assets/images/highlights/satpara_lake.jpg',
  'Shigar River': 'assets/images/highlights/upper_kachura_lake.jpg',
  'Serena Shigar Fort': 'assets/images/highlights/shigar_fort.jpg',
  'Amacha Garden': 'assets/images/highlights/shangrila_resort.jpg',
  'Traditional Villages': 'assets/images/highlights/traditional_villages.jpg',
  'Trekking Routes': 'assets/images/highlights/trekking_routes.jpg',

  // Naltar Valley (sample_data.dart)
  'Naltar Lakes': 'assets/images/highlights/deosai_plains.jpg',
  'Ski Resort': 'assets/images/highlights/malam_jabba.jpg',
  'Wildlife Spotting': 'assets/images/highlights/deosai_plains.jpg',
  'Naltar Pass': 'assets/images/highlights/babusar_top.jpg',
  'Blue Lake': 'assets/images/highlights/upper_kachura_lake.jpg',
  'Green Lake': 'assets/images/highlights/lower_kachura_lake.jpg',
  'Nomal Valley': 'assets/images/highlights/eagles_nest_duikar.jpg',
  'Camping Grounds': 'assets/images/highlights/camping_grounds.jpg',
  'Snow Covered Peaks': 'assets/images/highlights/snow_covered_peaks.jpg',
  'Star Gazing': 'assets/images/highlights/star_gazing.jpg',
};
